Add Github Omniauth
fastruby/ombu_labs-auth pull request #3
Opened 2022-10-14 19:07 UTC by tiagocasanovapt

2022-10-17 18:11 UTC, etagwerker requested changes
@tiagocasanovapt just one comment here.

2022-10-17 18:11 UTC, etagwerker commented on Gemfile
> +gem "omniauth-github"
@tiagocasanovapt No need to add this here. `gemspec` already defines devise and omniauth and omniauth-github as dependencies and you are including it in line 5.

2022-10-18 15:53 UTC, tiagocasanovapt commented on test/dummy/db/schema.rb
> -
leftovers from previous testing

2022-10-20 13:18 UTC, etagwerker approved these changes
@tiagocasanovapt Looks good, thanks!

2022-10-20 13:18 UTC, merged